=== Infineon/edgeprotecttools/src/targets/psoc_c3/schemas/debug_cert_schema.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "type": "object",
  "properties": {
    "version": {
      "type": "string"
    },
    "silicon_id": {
      "type": "string"
    },
    "family_id": {
      "type": "string"
    },
    "si_revision_id": {
      "type": "string"
    },
    "control_word": {
      "type": "object",
      "properties": {
        "cm33_ap": {
          "type": "string",
          "enum": [
            "Enable",
            "Disable"
          ]
        },
        "sys_ap": {
          "type": "string",
          "enum": [
            "Enable",
            "Disable"
          ]
        },
        "cm33_dbg": {
          "type": "string",
          "enum": [
            "Enable",
            "Disable"
          ]
        },
        "cm33_nid": {
          "type": "string",
          "enum": [
            "Enable",
            "Disable"
          ]
        },
        "cm33_spid": {
          "type": "string",
          "enum": [
            "Enable",
            "Disable"
          ]
        },
        "cm33_spnid": {
          "type": "string",
          "enum": [
            "Enable",
            "Disable"
          ]
        },
        "cm33_secure": {
          "type": "string",
          "enum": [
            "Enable",
            "Disable"
          ]
        },
        "sys_secure": {
          "type": "string",
          "enum": [
            "Enable",
            "Disable"
          ]
        },
        "rma": {
          "type": "string",
          "enum": [
            "Enable",
            "Disable"
          ]
        }
      },
      "required": [
        "cm33_ap",
        "sys_ap",
        "cm33_dbg",
        "cm33_nid",
        "cm33_spid",
        "cm33_spnid",
        "cm33_secure",
        "sys_secure",
        "rma"
      ]
    },
    "die_id": {
      "type": "object",
      "properties": {
        "max": {
          "type": "object",
          "properties": {
            "lot": {
              "type": "integer",
              "minimum": 0,
              "maximum": 16777215
            },
            "wafer": {
              "type": "integer",
              "minimum": 0,
              "maximum": 255
            },
            "xpos": {
              "type": "integer",
              "minimum": 0,
              "maximum": 255
            },
            "ypos": {
              "type": "integer",
              "minimum": 0,
              "maximum": 255
            },
            "sort": {
              "type": "integer",
              "minimum": 0,
              "maximum": 255
            },
            "minor": {
              "type": "integer",
              "minimum": 0,
              "maximum": 255
            },
            "day": {
              "type": "integer",
              "minimum": 0,
              "maximum": 255
            },
            "month": {
              "type": "integer",
              "minimum": 0,
              "maximum": 255
            },
            "year": {
              "type": "integer",
              "minimum": 0,
              "maximum": 255
            }
          },
          "required": [
            "lot",
            "wafer",
            "xpos",
            "ypos",
            "sort",
            "minor",
            "day",
            "month",
            "year"
          ]
        },
        "min": {
          "type": "object",
          "properties": {
            "lot": {
              "type": "integer",
              "minimum": 0,
              "maximum": 16777215
            },
            "wafer": {
              "type": "integer",
              "minimum": 0,
              "maximum": 255
            },
            "xpos": {
              "type": "integer",
              "minimum": 0,
              "maximum": 255
            },
            "ypos": {
              "type": "integer",
              "minimum": 0,
              "maximum": 255
            },
            "sort": {
              "type": "integer",
              "minimum": 0,
              "maximum": 255
            },
            "minor": {
              "type": "integer",
              "minimum": 0,
              "maximum": 255
            },
            "day": {
              "type": "integer",
              "minimum": 0,
              "maximum": 255
            },
            "month": {
              "type": "integer",
              "minimum": 0,
              "maximum": 255
            },
            "year": {
              "type": "integer",
              "minimum": 0,
              "maximum": 255
            }
          },
          "required": [
            "lot",
            "wafer",
            "xpos",
            "ypos",
            "sort",
            "minor",
            "day",
            "month",
            "year"
          ]
        }
      },
      "required": [
        "max",
        "min"
      ]
    }
  },
  "required": [
    "version",
    "silicon_id",
    "family_id",
    "si_revision_id",
    "control_word",
    "die_id"
  ]
}

=== Infineon/edgeprotecttools/src/targets/psoc_c3/packets/debug_token.json
{
  "version": "1.0.0.0",
  "silicon_id": "0xEE40",
  "family_id": "0x0118",
  "si_revision_id": "0x11",
  "control_word": {
    "cm33_ap": "Enable",
    "sys_ap": "Enable",
    "cm33_dbg": "Enable",
    "cm33_nid": "Enable",
    "cm33_spid": "Enable",
    "cm33_spnid": "Enable",
    "cm33_secure": "Enable",
    "sys_secure": "Enable",
    "rma": "Enable"
  },
  "die_id": {
    "min": {
      "lot": 0,
      "wafer": 0,
      "xpos": 0,
      "ypos": 0,
      "sort": 0,
      "minor": 0,
      "day": 0,
      "month": 0,
      "year": 0
    },
    "max": {
      "lot": 16777215,
      "wafer": 255,
      "xpos": 255,
      "ypos": 255,
      "sort": 255,
      "minor": 255,
      "day": 255,
      "month": 255,
      "year": 255
    }
  }
}
