=== Infineon/edgeprotecttools/src/targets/cyw559xx/schemas/key_cert_schema.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "type": "object",
  "properties": {
    "certificate": {
      "type": "object",
      "properties": {
        "type": {
          "type": "string",
          "enum": [
            "KEY_CERT"
          ]
        },
        "version": {
          "type": "number",
          "minimum": 1.0,
          "maximum": 1.0
        }
      },
      "required": [
        "type",
        "version"
      ]
    },
    "cert_keypair": {
      "type": "object",
      "properties": {
        "description": {
          "type": "string"
        },
        "value": {
          "type": "string"
        }
      },
      "required": [
        "value"
      ]
    },
    "cert_keypair_pwd": {
      "type": "object",
      "properties": {
        "description": {
          "type": "string"
        },
        "value": {
          "type": "string"
        }
      },
      "required": [
        "value"
      ]
    },
    "nv_counter": {
      "type": "object",
      "properties": {
        "description": {
          "type": "string"
        },
        "value": {
          "type": "integer",
          "minimum": 0,
          "maximum": 96
        }
      },
      "required": [
        "value"
      ]
    },
    "next_cert_pubkey": {
      "type": "object",
      "properties": {
        "description": {
          "type": "string"
        },
        "value": {
          "type": "string"
        }
      },
      "required": [
        "value"
      ]
    }
  },
  "required": [
    "certificate",
    "cert_keypair",
    "nv_counter",
    "next_cert_pubkey"
  ]
}

=== Infineon/edgeprotecttools/src/targets/cyw559xx/certs/key_cert_config.json
{
  "certificate": {
    "type": "KEY_CERT",
    "version": 1.0
  },
  "cert_keypair": {
    "description": "Path to the private key used to sign the certificate. The RSA key, 3072 bits in length",
    "value": ""
  },
  "cert_keypair_pwd": {
    "description": "Certificate private key password (if applicable)",
    "value": ""
  },
  "nv_counter": {
    "description": "Non-Volatile counter corresponding to the software version in the certificate",
    "value": 0
  },
  "next_cert_pubkey": {
    "description": "Path to the public key of the next certificate in the chain. The RSA key, 3072 bits in length",
    "value": ""
  }
}
