=== Infineon/edgeprotecttools/src/targets/cyw559xx/schemas/oem_provisioning_schema.json
{
    "$schema": "https://json-schema.org/draft/2020-12/schema",
    "title": "OEM Provisioning Schema",
    "type": "object",
    "required": [
        "policy",
        "oem_public_key",
        "provisioning_key",
        "code_encryption_key",
        "nv_counter"
    ],
    "properties": {
        "policy": {
            "type": "object",
            "required": [
                "platform",
                "version",
                "type"
            ],
            "properties": {
                "platform": {
                    "type": "string",
                    "const": "cyw559xx"
                },
                "version": {
                    "type": "number"
                },
                "type": {
                    "type": "string",
                    "const": "oem_provisioning"
                }
            }
        },
        "oem_public_key": {
            "type": "object",
            "required": [
                "value"
            ],
            "properties": {
                "value": {
                    "type": "string"
                }
            }
        },
        "provisioning_key": {
            "type": "object",
            "required": [
                "type",
                "data"
            ],
            "properties": {
                "type": {
                    "type": "object",
                    "required": [
                        "value"
                    ],
                    "properties": {
                        "value": {
                            "type": "string",
                            "enum": [
                                "ASSET_NO_KEY",
                                "ASSET_PLAIN_KEY"
                            ]
                        }
                    }
                },
                "data": {
                    "type": "object",
                    "required": [
                        "value"
                    ],
                    "properties": {
                        "value": {
                            "type": [
                                "string",
                                "null"
                            ]
                        }
                    }
                }
            }
        },
        "code_encryption_key": {
            "type": "object",
            "required": [
                "type",
                "data"
            ],
            "properties": {
                "type": {
                    "type": "object",
                    "required": [
                        "value"
                    ],
                    "properties": {
                        "value": {
                            "type": "string",
                            "enum": [
                                "ASSET_NO_KEY",
                                "ASSET_PLAIN_KEY"
                            ]
                        }
                    }
                },
                "data": {
                    "type": "object",
                    "required": [
                        "value"
                    ],
                    "properties": {
                        "value": {
                            "type": [
                                "string",
                                "null"
                            ]
                        }
                    }
                }
            }
        },
        "nv_counter": {
            "type": "object",
            "required": [
                "value"
            ],
            "properties": {
                "value": {
                    "type": "string"
                }
            }
        }
    }
}

=== Infineon/edgeprotecttools/src/targets/cyw559xx/policy/policy_oem_provisioning.json
{
  "policy": {
    "platform": "cyw559xx",
    "version": 1.0,
    "type": "oem_provisioning"
  },
  "oem_public_key": {
    "description": "Path to RSA public key",
    "value": "../keys/first_oem_pubkey.pem"
  },
  "provisioning_key": {
    "type": {
      "description": "Provisioning Key. Applicable values: ASSET_NO_KEY, ASSET_PLAIN_KEY",
      "value": "ASSET_NO_KEY"
    },
    "data": {
      "description": "Provisioning Key. Accepts hex string or path to binary file. If no key is provided, set the value to 'null'",
      "value": null
    }
  },
  "code_encryption_key": {
    "type": {
      "description": "Code Encryption Key. Applicable values: ASSET_NO_KEY, ASSET_PLAIN_KEY",
      "value": "ASSET_NO_KEY"
    },
    "data": {
      "description": "Code Encryption Key. Accepts hex string or path to binary file. If no key is provided, set the value to 'null'",
      "value": null
    }
  },
  "nv_counter": {
    "description": "Non-Volatile counter corresponding to the software version",
    "value": "0x00000000"
  }
}
